"""Initial Migration

Revision ID: 307e5833a64d
Revises: 
Create Date: 2023-05-16 20:03:34.883154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307e5833a64d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('log_content', sa.String(length=120), nullable=False),
    sa.Column('log_date_time', sa.DateTime(), nullable=False),
    sa.Column('system_version', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('physician',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('pwd', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('last_visit_date', sa.String(length=200), nullable=False),
    sa.Column('physician_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['physician_id'], ['physician.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient')
    op.drop_table('physician')
    op.drop_table('activity_log')
    # ### end Alembic commands ###
