"""Patient Active_Inactive Addedd

Revision ID: 7c7e5b2f981d
Revises: 9c1def4a8bf4
Create Date: 2023-05-17 18:12:17.722068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7e5b2f981d'
down_revision = '9c1def4a8bf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_inactive', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_invite_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('number_of_invites', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('invitation_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('baseline_survey_completion_status', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('baseline_survey_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('baseline_survey_completion_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('baseline_survey_wave_number', sa.Integer(), nullable=True))

    with op.batch_alter_table('physician', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baseline_survey_completion_status', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('baseline_survey_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('baseline_survey_completion_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('baseline_survey_wave_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physician', schema=None) as batch_op:
        batch_op.drop_column('baseline_survey_wave_number')
        batch_op.drop_column('baseline_survey_completion_date')
        batch_op.drop_column('baseline_survey_start_date')
        batch_op.drop_column('baseline_survey_completion_status')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('baseline_survey_wave_number')
        batch_op.drop_column('baseline_survey_completion_date')
        batch_op.drop_column('baseline_survey_start_date')
        batch_op.drop_column('baseline_survey_completion_status')
        batch_op.drop_column('invitation_sent')
        batch_op.drop_column('number_of_invites')
        batch_op.drop_column('last_invite_date')
        batch_op.drop_column('active_inactive')

    # ### end Alembic commands ###
