"""final Db changes done

Revision ID: c12d7ad95c16
Revises: 3fbbe2c29a3d
Create Date: 2023-05-21 14:19:51.663722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12d7ad95c16'
down_revision = '3fbbe2c29a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('baseline_survey_completion_status',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('followUp_one_completion_status',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('followUp_two_completion_status',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('new_prescription_treatment_start_date')

    with op.batch_alter_table('physician', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_prescription_treatment_start_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('baseline_survey_patient_id', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('followUp_one_patient_id', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('followUp_two_patient_id', sa.String(length=10), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('pwd',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('baseline_survey_completion_status',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('followUp_one_completion_status',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('followUp_two_completion_status',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('followUp_two_completion_date',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physician', schema=None) as batch_op:
        batch_op.alter_column('followUp_two_completion_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('followUp_two_completion_status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('followUp_one_completion_status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('baseline_survey_completion_status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('pwd',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('followUp_two_patient_id')
        batch_op.drop_column('followUp_one_patient_id')
        batch_op.drop_column('baseline_survey_patient_id')
        batch_op.drop_column('new_prescription_treatment_start_date')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_prescription_treatment_start_date', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('followUp_two_completion_status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('followUp_one_completion_status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('baseline_survey_completion_status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###
