"""Patient New Presecription Added

Revision ID: c159d69c0a17
Revises: 7c7e5b2f981d
Create Date: 2023-05-17 19:13:21.796986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c159d69c0a17'
down_revision = '7c7e5b2f981d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_prescription_treatment_start_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('followUp_one_survey_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('followUp_one_completion_status', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('followUp_one_completion_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('followUp_one_wave_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('followUp_two_survey_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('followUp_two_completion_status', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('followUp_two_completion_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('followUp_two_wave_number', sa.Integer(), nullable=True))

    with op.batch_alter_table('physician', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followUp_one_survey_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('followUp_one_completion_status', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('followUp_one_completion_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('followUp_one_wave_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('followUp_two_survey_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('followUp_two_completion_status', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('followUp_two_completion_date', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('followUp_two_wave_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physician', schema=None) as batch_op:
        batch_op.drop_column('followUp_two_wave_number')
        batch_op.drop_column('followUp_two_completion_date')
        batch_op.drop_column('followUp_two_completion_status')
        batch_op.drop_column('followUp_two_survey_start_date')
        batch_op.drop_column('followUp_one_wave_number')
        batch_op.drop_column('followUp_one_completion_date')
        batch_op.drop_column('followUp_one_completion_status')
        batch_op.drop_column('followUp_one_survey_start_date')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('followUp_two_wave_number')
        batch_op.drop_column('followUp_two_completion_date')
        batch_op.drop_column('followUp_two_completion_status')
        batch_op.drop_column('followUp_two_survey_start_date')
        batch_op.drop_column('followUp_one_wave_number')
        batch_op.drop_column('followUp_one_completion_date')
        batch_op.drop_column('followUp_one_completion_status')
        batch_op.drop_column('followUp_one_survey_start_date')
        batch_op.drop_column('new_prescription_treatment_start_date')

    # ### end Alembic commands ###
