"""Initial Migration

Revision ID: f27e4159028c
Revises: 
Create Date: 2023-05-18 02:47:06.930190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27e4159028c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('log_content', sa.String(length=120), nullable=False),
    sa.Column('log_date_time', sa.DateTime(), nullable=False),
    sa.Column('system_version', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('physician',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('pwd', sa.String(length=256), nullable=False),
    sa.Column('baseline_survey_completion_status', sa.String(length=256), nullable=True),
    sa.Column('baseline_survey_start_date', sa.Date(), nullable=True),
    sa.Column('baseline_survey_completion_date', sa.Date(), nullable=True),
    sa.Column('baseline_survey_wave_number', sa.Integer(), nullable=True),
    sa.Column('followUp_one_survey_start_date', sa.Date(), nullable=True),
    sa.Column('followUp_one_completion_status', sa.String(length=256), nullable=True),
    sa.Column('followUp_one_completion_date', sa.Date(), nullable=True),
    sa.Column('followUp_one_wave_number', sa.Integer(), nullable=True),
    sa.Column('followUp_two_survey_start_date', sa.Date(), nullable=True),
    sa.Column('followUp_two_completion_status', sa.String(length=256), nullable=True),
    sa.Column('followUp_two_completion_date', sa.String(length=256), nullable=True),
    sa.Column('followUp_two_wave_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('last_visit_date', sa.String(length=200), nullable=True),
    sa.Column('physician_id', sa.String(), nullable=False),
    sa.Column('active_inactive', sa.Boolean(), nullable=True),
    sa.Column('last_invite_date', sa.Date(), nullable=True),
    sa.Column('number_of_invites', sa.Integer(), nullable=True),
    sa.Column('invitation_sent', sa.Boolean(), nullable=True),
    sa.Column('new_prescription_treatment_start_date', sa.String(length=20), nullable=True),
    sa.Column('baseline_survey_completion_status', sa.String(length=256), nullable=True),
    sa.Column('baseline_survey_start_date', sa.Date(), nullable=True),
    sa.Column('baseline_survey_completion_date', sa.Date(), nullable=True),
    sa.Column('baseline_survey_wave_number', sa.Integer(), nullable=True),
    sa.Column('followUp_one_survey_start_date', sa.Date(), nullable=True),
    sa.Column('followUp_one_completion_status', sa.String(length=256), nullable=True),
    sa.Column('followUp_one_completion_date', sa.Date(), nullable=True),
    sa.Column('followUp_one_wave_number', sa.Integer(), nullable=True),
    sa.Column('followUp_two_survey_start_date', sa.Date(), nullable=True),
    sa.Column('followUp_two_completion_status', sa.String(length=256), nullable=True),
    sa.Column('followUp_two_completion_date', sa.Date(), nullable=True),
    sa.Column('followUp_two_wave_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['physician_id'], ['physician.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient')
    op.drop_table('physician')
    op.drop_table('activity_log')
    # ### end Alembic commands ###
